export const Carreras = [

{ label: "Arquitectura" , value: "Arquitectura" },
{ label: "Ingeniería Civil" , value: "Ingeniería Civil" },
{ label: "Ingeniería Civil en Gestión de la Construcción" , value: "Ingeniería Civil en Gestión de la Construcción" },
{ label: "Ingeniería Civil Plan Común" , value: "Ingeniería Civil Plan Común" },
{ label: "Ingeniería en Construcción" , value: "Ingeniería en Construcción" },
{ label: "Ingeniería en Prevención de Riesgos y Medioambiente" , value: "Ingeniería en Prevención de Riesgos y Medioambiente" },
{ label: "Analista Químico" , value: "Analista Químico" },
{ label: "Geología" , value: "Geología" },
{ label: "Licenciatura en Física con mención en Astronomía" , value: "Licenciatura en Física con mención en Astronomía" },
{ label: "Licenciatura en Matemática" , value: "Licenciatura en Matemática" },
{ label: "Química Industrial" , value: "Química Industrial" },
{ label: "Biología Marina" , value: "Biología Marina" },
{ label: "Ingeniería en Acuicultura" , value: "Ingeniería en Acuicultura" },
{ label: "Contador Auditor - Contador Público Diurno" , value: "Contador Auditor - Contador Público Diurno" },
{ label: "Contador Auditor - Contador Público Vespertino" , value: "Contador Auditor - Contador Público Vespertino" },
{ label: "Ingeniería Comercial" , value: "Ingeniería Comercial" },
{ label: "Ingeniería en Información y Control de Gestión" , value: "Ingeniería en Información y Control de Gestión" },
{ label: "Derecho" , value: "Derecho" },
{ label: "Periodismo" , value: "Periodismo" },
{ label: "Psicología" , value: "Psicología" },
{ label: "Ingeniería Civil Ambiental" , value: "Ingeniería Civil Ambiental" },
{ label: "Ingeniería Civil de Minas" , value: "Ingeniería Civil de Minas" },
{ label: "Ingeniería Civil Industrial" , value: "Ingeniería Civil Industrial" },
{ label: "Ingeniería Civil Metalúrgica" , value: "Ingeniería Civil Metalúrgica" },
{ label: "Ingeniería Civil Plan Común" , value: "Ingeniería Civil Plan Común" },
{ label: "Ingeniería Civil Química" , value: "Ingeniería Civil Química" },
{ label: "Ingeniería en Metalurgia" , value: "Ingeniería en Metalurgia" },
{ label: "Ingeniería en Prevención de Riesgos y Medioambiente" , value: "Ingeniería en Prevención de Riesgos y Medioambiente" },
{ label: "Pedagogía en Educación Básica con Especialización" , value: "Pedagogía en Educación Básica con Especialización" },
{ label: "Pedagogía en Educación Diferencial con Mención en Desarrollo Emocional y Cognitivo" , value: "Pedagogía en Educación Diferencial con Mención en Desarrollo Emocional y Cognitivo" },
{ label: "Pedagogía en Educación Parvularia con Mención en Desarrollo Emocional y Cognitivo" , value: "Pedagogía en Educación Parvularia con Mención en Desarrollo Emocional y Cognitivo" },
{ label: "Pedagogía en Filosofía y Religión" , value: "Pedagogía en Filosofía y Religión" },
{ label: "Pedagogía en Inglés" , value: "Pedagogía en Inglés" },
{ label: "Pedagogía en Matemática en Educación Media" , value: "Pedagogía en Matemática en Educación Media" },
{ label: "Enfermería" , value: "Enfermería" },
{ label: "Kinesiología" , value: "Kinesiología" },
{ label: "Medicina" , value: "Medicina" },
{ label: "Nutrición y Dietética" , value: "Nutrición y Dietética" },
{ label: "Química y Farmacia" , value: "Química y Farmacia" },
{ label: "Ingeniería Civil en Computación e Informática" , value: "Ingeniería Civil en Computación e Informática" },
{ label: "Ingeniería Civil Plan Común" , value: "Ingeniería Civil Plan Común" },
{ label: "Ingeniería en Computación e Informática" , value: "Ingeniería en Computación e Informática" },
{ label: "Ingeniería en Tecnologías de Información" , value: "Ingeniería en Tecnologías de Información" },
{ label: "Licenciatura en Ciencias Religiosas" , value: "Licenciatura en Ciencias Religiosas" },
{ label: "Pedagogía en Filosofía y Religión" , value: "Pedagogía en Filosofía y Religión" },
{ label: "Programa de Prosecución de Estudios de Formación Pedagógica" , value: "Programa de Prosecución de Estudios de Formación Pedagógica" },

]
   

